In [109]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
import warnings

In [126]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
#print(df.head())

In [127]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

tenure = np.array(df['tenure'])
monthlycharges = np.array(df['MonthlyCharges'])
totalcharges = np.array(df['TotalCharges'])
#print(X_train)
categorical_columns = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
                       'PaperlessBilling', 'PaymentMethod', 'Churn']

numerical_columns = ['tenure', 'MonthlyCharges', 'TotalCharges']

#for col in categorical_columns:
#    le = preprocessing.LabelEncoder()
#    df[col] = le.fit_transform(df[col])


In [131]:
enc = preprocessing.LabelEncoder()
for col in categorical_columns:
    enc = preprocessing.LabelEncoder()
    df[col] = enc.fit_transform(df[col])

#print(df.head())
print(df)

      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     7590-VHVEG       0              0        1           0       1   
1     5575-GNVDE       1              0        0           0      34   
2     3668-QPYBK       1              0        0           0       2   
3     7795-CFOCW       1              0        0           0      45   
4     9237-HQITU       0              0        0           0       2   
...          ...     ...            ...      ...         ...     ...   
7038  6840-RESVB       1              0        1           1      24   
7039  2234-XADUH       0              0        1           1      72   
7040  4801-JZAZL       0              0        1           1      11   
7041  8361-LTMKD       1              1        1           0       4   
7042  3186-AJIEK       1              0        0           0      66   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0                0              1                0          

In [132]:
#df['TotalCharges'] = pd.to_numeric(df['TotalCharges'].round(2), errors='coerce').fillna(0).astype(float)
#df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0).astype(float)
#print(df)
X_train=np.array(df)
X_train[X_train[:, 19] == ' ', 19] = '0'
X_train[:, 19] = X_train[:, 19].astype(float)
#print(X_train)
Y_train = np.delete(X_train,0,1)
#Y_train[:, 18] = Y_train[:, 18].astype(float)
#Y_train[18] = pd.to_numeric(Y_train[18], errors='coerce').fillna(0).astype(float)
print(Y_train)

[[0 0 1 ... 29.85 29.85 0]
 [1 0 0 ... 56.95 1889.5 0]
 [1 0 0 ... 53.85 108.15 1]
 ...
 [0 0 1 ... 29.6 346.45 0]
 [1 1 1 ... 74.4 306.6 1]
 [1 0 0 ... 105.65 6844.5 0]]


In [133]:
#Y_train = np.delete(X_train,0,1)
Y_train_numerical = Y_train[:, [4, 17,18]]
#Y_train_numerical
Y_train_categorical = Y_train[:,[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,19]]
print(Y_train_numerical)
print(Y_train_categorical)

[[1 29.85 29.85]
 [34 56.95 1889.5]
 [2 53.85 108.15]
 ...
 [11 29.6 346.45]
 [4 74.4 306.6]
 [66 105.65 6844.5]]
[[0 0 1 ... 1 2 0]
 [1 0 0 ... 0 3 0]
 [1 0 0 ... 1 3 1]
 ...
 [0 0 1 ... 1 2 0]
 [1 1 1 ... 1 3 1]
 [1 0 0 ... 1 0 0]]


In [134]:
Y_normalized_numerical=preprocessing.normalize(Y_train_numerical, norm='l2')

In [136]:
Y_normalized_categorical=preprocessing.normalize(Y_train_categorical, norm='l2')

In [143]:
print(Y_normalized_numerical)
print(Y_normalized_categorical)

[[0.02368203 0.70690847 0.70690847]
 [0.0179831  0.0301217  0.99938446]
 [0.01655198 0.44566203 0.89504826]
 ...
 [0.03161954 0.08508531 0.99587183]
 [0.01267735 0.23579879 0.97171921]
 [0.00964118 0.0154332  0.99983442]]
[[0.         0.         0.30151134 ... 0.30151134 0.60302269 0.        ]
 [0.2236068  0.         0.         ... 0.         0.67082039 0.        ]
 [0.21821789 0.         0.         ... 0.21821789 0.65465367 0.21821789]
 ...
 [0.         0.         0.28867513 ... 0.28867513 0.57735027 0.        ]
 [0.2236068  0.2236068  0.2236068  ... 0.2236068  0.67082039 0.2236068 ]
 [0.18898224 0.         0.         ... 0.18898224 0.         0.        ]]


In [145]:
min_max_scaler = preprocessing.MinMaxScaler()
Y_train_minmax=min_max_scaler.fit_transform(Y_normalized_categorical)
Y_train_minmax
print("mean:", Y_train_minmax.mean(axis=0), ", std:", Y_train_minmax.std(axis=0))

mean: [0.16608755 0.06556478 0.14978514 0.09315514 0.21149859 0.20304483
 0.28287013 0.18837171 0.2151798  0.23135366 0.20470904 0.25329119
 0.27574243 0.19957911 0.19573299 0.37971161 0.11480506] , std: [0.17426184 0.15357552 0.16164188 0.14682554 0.08958057 0.20832611
 0.24439081 0.20828919 0.21204728 0.22634302 0.2227958  0.22937893
 0.24798828 0.23968905 0.17389986 0.26137723 0.19827027]


In [ ]:
min_max_scaler2 = preprocessing.MinMaxScaler()
Y_train_minmax2=min_max_scaler2.fit_transform(Y_train_categorical)
Y_train_minmax2
#print("mean:", Y_train_minmax2.mean(axis=0), ", std:", Y_train_minmax2.std(axis=0))

In [138]:
#scaler = preprocessing.StandardScaler().fit(Y_train_numerical)
#scaler
#Y_scaled_numerical=scaler.transform(Y_train_numerical)
#Y_scaled_numerical

In [139]:
#scaler = preprocessing.StandardScaler().fit(Y_train_categorical)
#scaler
#Y_scaled_categorical=scaler.transform(Y_train_categorical)
#Y_scaled_categorical

In [140]:
#print("mean:", Y_scaled_numerical.mean(axis=0), ", std:", Y_scaled_numerical.std(axis=0))

In [141]:
min_max_scaler = preprocessing.MinMaxScaler()
Y_train_minmax=min_max_scaler.fit_transform(Y_train_numerical)
Y_train_minmax
print("mean:", Y_train_minmax.mean(axis=0), ", std:", Y_train_minmax.std(axis=0))

mean: [0.44959929 0.46280291 0.26249704] , std: [0.34107969 0.2993822  0.26098857]


In [142]:
min_max_scaler2 = preprocessing.MinMaxScaler()
Y_train_minmax2=min_max_scaler2.fit_transform(Y_train_categorical)
Y_train_minmax2
#print("mean:", Y_train_minmax2.mean(axis=0), ", std:", Y_train_minmax2.std(axis=0))

mean: [0.5047565  0.16214681 0.4830328  0.29958824 0.90316626 0.47025415
 0.43646174 0.39500213 0.45321596 0.45222206 0.39855175 0.49268778
 0.4962374  0.3452364  0.59221922 0.52477637 0.26536987] , std: [0.49997738 0.36858544 0.49971203 0.45807764 0.29573123 0.47424335
 0.36887198 0.42989323 0.44004999 0.43994319 0.4307447  0.44246952
 0.44251394 0.41684802 0.49142203 0.35600939 0.44152996]
