In [1]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
from sklearn import preprocessing
import warnings

In [78]:
#df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
#print(df.head())

In [68]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

tenure = np.array(df['tenure'])
monthlycharges = np.array(df['MonthlyCharges'])
totalcharges = np.array(df['TotalCharges'])
X_train=np.array(df)
#print(X_train)
categorical_columns = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
                       'PaperlessBilling', 'PaymentMethod', 'Churn']

numerical_columns = ['tenure', 'MonthlyCharges', 'TotalCharges']

#for col in categorical_columns:
#    le = preprocessing.LabelEncoder()
#    df[col] = le.fit_transform(df[col])

enc = preprocessing.LabelEncoder()
for col in categorical_columns:
    enc = preprocessing.LabelEncoder()
    df[col] = enc.fit_transform(df[col])

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'].round(2), errors='coerce').fillna(0).astype(float)
Y_train = np.delete(X_train,0,1)
#print(Y_train)

Y_train = np.delete(X_train,0,1)
Y_train_numerical = Y_train[:, [4, 17,18]]
Y_train_numerical
Y_train_categorical = Y_train[:,[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,19]]
print(Y_train_numerical)
print(Y_train_categorical)

[[1 29.85 29.85]
 [34 56.95 1889.5]
 [2 53.85 108.15]
 ...
 [11 29.6 346.45]
 [4 74.4 306.6]
 [66 105.65 6844.5]]
[[0 0 1 ... 1 2 0]
 [1 0 0 ... 0 3 0]
 [1 0 0 ... 1 3 1]
 ...
 [0 0 1 ... 1 2 0]
 [1 1 1 ... 1 3 1]
 [1 0 0 ... 1 0 0]]


In [72]:
Y_normalized_numerical=preprocessing.normalize(Y_train_numerical, norm='l2')
Y_normalized_categorical=preprocessing.normalize(Y_train_categorical, norm='l2')

In [75]:
#scaler = preprocessing.StandardScaler().fit(Y_train_numerical)
#scaler
#Y_scaled_numerical=scaler.transform(Y_train_numerical)
#Y_scaled_numerical

In [76]:
#scaler = preprocessing.StandardScaler().fit(Y_train_categorical)
#scaler
#Y_scaled_categorical=scaler.transform(Y_train_categorical)
#Y_scaled_categorical

In [55]:
print("mean:", Y_scaled_numerical.mean(axis=0), ", std:", Y_scaled_numerical.std(axis=0))

mean: [-2.42127299e-17 -6.40628478e-17 -3.78323904e-17] , std: [1. 1. 1.]


In [73]:
min_max_scaler = preprocessing.MinMaxScaler()
Y_train_minmax=min_max_scaler.fit_transform(Y_train_numerical)
Y_train_minmax
print("mean:", Y_scaled_numerical.mean(axis=0), ", std:", Y_scaled_numerical.std(axis=0))

mean: [-2.42127299e-17 -6.40628478e-17 -3.78323904e-17] , std: [1. 1. 1.]


In [74]:
min_max_scaler2 = preprocessing.MinMaxScaler()
Y_train_minmax2=min_max_scaler2.fit_transform(Y_train_categorical)
Y_train_minmax2
print("mean:", Y_scaled_categorical.mean(axis=0), ", std:", Y_scaled_categorical.std(axis=0))

mean: [-2.21950024e-17 -4.84254598e-17  7.16293259e-17  1.06939557e-16
  7.86913721e-17 -1.51329562e-17  8.57534183e-18  6.80983028e-17
  2.29516502e-17 -4.53988685e-17 -3.12747761e-17  2.16905705e-17
  7.06204622e-18 -7.56647809e-17 -5.95229610e-17 -1.16019331e-17
 -7.66736446e-17] , std: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
